import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f7fb',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#007bff',
    marginLeft: 4,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: 8,
  },
  cardsList: {
    marginBottom: 16,
  },
  cardsContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: 16,
    elevation: 2,
    shadowColor: '#fff',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  cardItem: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 1,
    shadowColor: '#fff',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  cardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardBrandBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#eef2ff',
    marginRight: 10,
  },
  cardBrandText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111827',
  },
  cardTextWrapper: {
    justifyContent: 'center',
  },
  cardNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  cardHolder: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  cardRight: {
    alignItems: 'flex-end',
  },
  cardType: {
    fontSize: 12,
    color: '#6b7280',
  },
  cardExpiry: {
    fontSize: 12,
    color: '#111827',
    fontWeight: '500',
    marginTop: 4,
  },
  cardSelectedIcon: {
    marginTop: 6,
  },
  primaryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryTopNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  primaryCardWrapper: {
    marginBottom: 8,
  },
  primaryCard: {
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 18,
    backgroundColor: '#5B4FE9',
  },
  primaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  primaryBrand: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  primaryDateLabel: {
    fontSize: 10,
    color: '#e5e7eb',
    marginBottom: 4,
    textAlign: 'right',
  },
  primaryExpiry: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'right',
  },
  primaryNumberLabel: {
    fontSize: 10,
    color: '#e5e7eb',
  },
  primaryNumber: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    marginTop: 4,
  },
  primaryFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  primaryFooterCol: {
    flex: 1,
  },
  primaryFooterLabel: {
    fontSize: 10,
    color: '#e5e7eb',
  },
  primaryFooterValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
    marginTop: 4,
  },
  addCardButton: {
    display: 'none',
  },
  addCardLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#007bff',
  },
  scanSection: {
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  scanIcon: {
    marginBottom: 6,
  },
  scanLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#007bff',
  },
  amountLabel: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 4,
  },
  amountInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#007bff',
    paddingVertical: 6,
    fontSize: 16,
    color: '#111827',
    marginBottom: 20,
  },
  addCardPrimaryButton: {
    marginHorizontal: 16,
    marginBottom: 24,
    backgroundColor: '#007bff',
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addCardPrimaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  disabledButton: {
    opacity: 0.4,
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 16,
    textAlign: 'center',
  },
  inputLabel: {
    fontSize: 13,
    color: '#4b5563',
    marginTop: 8,
    marginBottom: 4,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: '#111827',
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dropdownText: {
    fontSize: 14,
    color: '#111827',
  },
  dropdownList: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    marginTop: 4,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
  },
  dropdownItemText: {
    fontSize: 14,
    color: '#111827',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    marginRight: 8,
  },
  submitButton: {
    backgroundColor: '#007bff',
    marginLeft: 8,
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  cancelButtonText: {
    color: '#111827',
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 12,
    marginTop: 6,
  },
  cameraOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  cameraFrame: {
    width: '100%',
    height: '70%',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#10b981',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraHint: {
    fontSize: 14,
    color: '#e5e7eb',
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  cameraActions: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  cameraSimButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4b5563',
    marginHorizontal: 4,
    alignItems: 'center',
  },
  cameraSimText: {
    fontSize: 12,
    color: '#e5e7eb',
  },
  confirmModalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
  },
  confirmText: {
    fontSize: 15,
    color: '#111827',
    textAlign: 'center',
    marginBottom: 16,
  },
  successText: {
    fontSize: 14,
    color: '#16a34a',
    textAlign: 'center',
    marginTop: 8,
  },
});

